config/routes.rb
Rails.application.routes.draw do
  concern :commentable do
    resources :comments, only: %i[index create]
  end

  get 'charts/show', as: :chart
  resources :applicants, concerns: :commentable do
    patch :change_stage, on: :member
    resources :emails, only: %i[index new create show]
    resources :email_replies, only: %i[new]
    get :resume, action: :show, controller: 'resumes'
  end
  
  resources :invites, only: %i[create update]
  resources :jobs
  resources :notifications, only: %i[index]
  resources :users
  get 'invite', to: 'invites#new', as: 'accept_invite'

  devise_for :users,
    path: '',
    controllers: {
      registrations: 'users/registrations'
    },
    path_names: {
      sign_in: 'login',
      password: 'forgot',
      confirmation: 'confirm',
      sign_up: 'sign_up',
      sign_out: 'signout'
    }
  get 'dashboard/show'

  namespace :careers do
    resources :accounts, only: %i[show] do
      resources :jobs, only: %i[index show], shallow: true do
        resources :applicants, only: %i[new create]
      end
    end
  end

  authenticated :user do
    root to: 'dashboard#show', as: :user_root
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def new
    @user = User.find_by(invite_token: params[:token])
    unless params[:token].present? && @user.present?
      redirect_to root_path, error: 'Invalid invitation code'
    end
  end

  def create
    @user = User.find_by(invite_token: params[:user][:token])
    if @user && @user.update(user_params)
      @user.update_columns(invite_token: nil, accepted_invite_at: Time.current)
      sign_in(@user)
      flash[:success] = 'Invite accepted. Welcome to Hotwired ATS!'
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    @user.reset_invite!(current_user)
    UserInviteMailer.invite(@user).deliver_later
    flash_html = render_to_string(partial: 'shared/flash', locals: { level: :success, content: "Resent invite to #{@user.name}" })
    render operations: cable_car
      .inner_html('#flash-container', html: flash_html)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :password)
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/new.html.erb
<div class="flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-lg">
    <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
      Welcome to Hotwired ATS
    </h2>
  </div>

  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-lg">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <%= form_with(model: @user, url: invites_path, method: :post, html: { class: "space-y-6" }) do |form| %>
        <%= form.hidden_field :token, value: params[:token] %>

        <div class="form-group">
          <%= form.label :first_name %>
          <div class="mt-1">
            <%= form.text_field :first_name, autofocus: true %>
          </div>
        </div>

        <div class="form-group">
          <%= form.label :last_name %>
          <div class="mt-1">
            <%= form.text_field :last_name, autofocus: true %>
          </div>
        </div>

        <div class="form-group">
          <%= form.label :password %>
          <div class="mt-1">
            <%= form.password_field :password, autocomplete: "current-password" %>
          </div>
        </div>

        <div>
          <%= form.button 'Accept invite', class: "btn-primary w-full", data: { disable_with: 'Submitting' } %>
        </div>
      <% end %>
    </div>
  </div>
</div>