config/routes.rb
Rails.application.routes.draw do
  concern :commentable do
    resources :comments, only: %i[index create]
  end

  get 'charts/show', as: :chart
  resources :applicants, concerns: :commentable do
    patch :change_stage, on: :member
    resources :emails, only: %i[index new create show]
    resources :email_replies, only: %i[new]
    get :resume, action: :show, controller: 'resumes'
  end
  
  resources :invites, only: %i[create update]
  resources :jobs
  resources :notifications, only: %i[index]
  resources :users
  get 'invite', to: 'invites#new', as: 'accept_invite'

  devise_for :users,
    path: '',
    controllers: {
      registrations: 'users/registrations'
    },
    path_names: {
      sign_in: 'login',
      password: 'forgot',
      confirmation: 'confirm',
      sign_up: 'sign_up',
      sign_out: 'signout'
    }
  get 'dashboard/show'

  namespace :careers do
    resources :accounts, only: %i[show] do
      resources :jobs, only: %i[index show], shallow: true do
        resources :applicants, only: %i[new create]
      end
    end
  end

  authenticated :user do
    root to: 'dashboard#show', as: :user_root
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/models/job.rb
class Job < ApplicationRecord
  FILTER_PARAMS = %i[query status sort].freeze

  belongs_to :account
  has_many :applicants, dependent: :destroy

  validates_presence_of :title, :status, :job_type, :location

  enum status: {
    draft: 'draft',
    open: 'open',
    closed: 'closed'
  }

  enum job_type: {
    full_time: 'full_time',
    part_time: 'part_time'
  }

  has_rich_text :description

  scope :for_account, ->(account_id) { where(account_id: account_id) }
  scope :for_status, ->(status) { status.present? ? where(status: status) : all }
  scope :search_by_title, ->(query) { query.present? ? where('title ILIKE ?', "%#{query}%") : all }
  scope :sorted, ->(selection) { selection.present? ? apply_sort(selection) : all }

  def self.filter(filters)
    search_by_title(filters['query'])
      .for_status(filters['status'])
      .sorted(filters['sort'])
  end

  def self.apply_sort(selection)
    return if selection.blank?

    sort, direction = selection.split('-')
    order("#{sort} #{direction}")
  end
end

app/controllers/careers/jobs_controller.rb
class Careers::JobsController < CareersController
  before_action :set_account, only: %i[index]
  before_action :set_job, only: %i[show]

  def index
    @jobs = @account.jobs.open.order(title: :asc)
  end

  def show
    @account = @job.account
  end

  private

  def set_job
    @job = Job.includes(:account).find(params[:id])
  end

  def set_account
    @account = Account.find(params[:account_id])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  include Filterable

  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @jobs = filter!(Job).for_account(current_user.account_id)
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    html = render_to_string(partial: 'form', locals: { job: Job.new })
    render operations: cable_car
      .inner_html('#slideover-content', html: html)
      .text_content('#slideover-header', text: 'Post a new job')
  end

  # GET /jobs/1/edit
  def edit
    html = render_to_string(partial: 'form', locals: { job: @job })
    render operations: cable_car
      .inner_html('#slideover-content', html: html)
      .text_content('#slideover-header', text: 'Update job')
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)
    @job.account = current_user.account
    if @job.save
      html = render_to_string(partial: 'job', locals: { job: @job })
      render operations: cable_car
        .prepend('#jobs', html: html)
        .dispatch_event(name: 'submit:success')
    else
      html = render_to_string(partial: 'form', locals: { job: @job })
      render operations: cable_car
        .inner_html('#job-form', html: html), status: :unprocessable_entity
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    if @job.update(job_params)
      html = render_to_string(partial: 'job', locals: { job: @job })
      render operations: cable_car
        .replace(dom_id(@job), html: html)
        .dispatch_event(name: 'submit:success')
    else
      html = render_to_string(partial: 'form', locals: { job: @job })
      render operations: cable_car
        .inner_html('#job-form', html: html), status: :unprocessable_entity
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    render operations: cable_car.remove(selector: dom_id(@job))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :status, :job_type, :location, :account_id, :description)
    end
end

app/helpers/careers/jobs_helper.rb
module Careers::JobsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def job_sort_options_for_select
    [
      ['Posting Date Ascending', 'created_at-asc'],
      ['Posting Date Descending', 'created_at-desc'],
      ['Title Ascending', 'title-asc'],
      ['Title Descending', 'title-desc']
    ]
  end

  def status_options_for_select
    Job.statuses.map{|key, _value| [key.humanize, key]}
  end
end

app/views/jobs/_filter_form.html.erb
<%= form_with url: jobs_path, method: :get, class: "flex items-baseline", data: { controller: "form", form_target: "form", turbo_frame: "jobs", turbo_action: "advance" } do |form| %>
  <div class="form-group mr-2">
    <%= form.label :sort, class: "sr-only" %>
    <%= form.select :sort,
      options_for_select(job_sort_options_for_select, fetch_filter_key("job", current_user.id, 'sort')),
      {},
      { data: { action: "change->form#submit" } }
    %>
  </div>
  <div class="form-group mr-2">
    <%= form.label :status, class: "sr-only" %>
    <%= form.select :status,
      options_for_select(status_options_for_select, fetch_filter_key("job", current_user.id, 'status')),
      { include_blank: 'All Statuses' },
      { data: { action: "change->form#submit" } }
    %>
  </div>
  <div class="form-group mr-2">
    <%= form.label :query, class: "sr-only" %>
    <%= form.text_field :query, placeholder: "Search jobs", value: fetch_filter_key("job", current_user.id, 'query'), data: { action: "input->form#submit" } %>
  </div>
<% end %>

app/views/jobs/_form.html.erb
<%= form_with(
  model: job,
  id: 'job-form',
  html: { class: "space-y-6" },
  data: { remote: true }
) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <div class="mt-1">
      <%= form.text_field :title %>
    </div>
  </div>

  <div class="form-group">
    <%= form.rich_text_area :description %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Job.statuses.map{|key, _value| [key.humanize, key]}, job.status), {}, { class: "mt-1" } %>
  </div>

  <div class="form-group">
    <%= form.label :job_type %>
    <%= form.select :job_type, options_for_select(Job.job_types.map{|key, _value| [key.humanize, key]}, job.job_type), {}, { class: "mt-1" } %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <div class="mt-1">
      <%= form.text_field :location %>
    </div>
  </div>

  <%= form.submit 'Submit', class: 'btn-primary float-right' %>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id(job) %>">
  <div class="flex flex-col md:flex-row items-center px-4 py-4 sm:px-6 justify-between">
    <div class="flex-1">
      <%= link_to job.title,
        edit_job_path(job),
        class: "text-lg text-blue-600 hover:text-blue-700",
        data: {
          action: "click->slideover#open",
          remote: true
        } %>
      <div class="flex space-x-2 text-gray-500 text-sm">
        <div>
          <%= job.location %>
        </div>
        <div>
          <%= job.job_type.humanize %>
        </div>
      </div>
    </div>
    <div class="text-right">
      <%= button_to "Delete job",
        job_path(job),
        method: :delete,
        class: "btn border border-red-200 hover:bg-red-100 text-sm text-red-700",
        remote: true,
        data: {
          confirm: "Are you sure?"
        } %>
    </div>
  </div>
</div>

app/views/jobs/_list.html.erb
<%= turbo_frame_tag "jobs", class: "divide-y divide-gray-200" do %>
  <%= render jobs %>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html+turbo_frame.erb
<%= render "list", jobs: @jobs %>

app/views/jobs/index.html.erb
<div class="flex items-baseline justify-between mb-6">
  <h2 class="mt-6 text-3xl font-extrabold text-gray-700">
    Jobs
  </h2>
  <%= link_to "Post a new job", new_job_path, class: "btn-primary-outline", data: { action: "mouseup->slideover#open", remote: true } %>
</div>
<div class="flex mb-6 justify-end">
  <%= render "filter_form" %>
</div>
<div class="shadow overflow-hidden sm:rounded-md">
  <%= render "list", jobs: @jobs %>
</div>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job %>

<div>
  <%= link_to "Edit this job", edit_job_path(@job) %> |
  <%= link_to "Back to jobs", jobs_path %>

  <%= button_to "Destroy this job", @job, method: :delete %>
</div>