config/routes.rb
Rails.application.routes.draw do
  concern :commentable do
    resources :comments, only: %i[index create]
  end

  get 'charts/show', as: :chart
  resources :applicants, concerns: :commentable do
    patch :change_stage, on: :member
    resources :emails, only: %i[index new create show]
    resources :email_replies, only: %i[new]
    get :resume, action: :show, controller: 'resumes'
  end
  
  resources :invites, only: %i[create update]
  resources :jobs
  resources :notifications, only: %i[index]
  resources :users
  get 'invite', to: 'invites#new', as: 'accept_invite'

  devise_for :users,
    path: '',
    controllers: {
      registrations: 'users/registrations'
    },
    path_names: {
      sign_in: 'login',
      password: 'forgot',
      confirmation: 'confirm',
      sign_up: 'sign_up',
      sign_out: 'signout'
    }
  get 'dashboard/show'

  namespace :careers do
    resources :accounts, only: %i[show] do
      resources :jobs, only: %i[index show], shallow: true do
        resources :applicants, only: %i[new create]
      end
    end
  end

  authenticated :user do
    root to: 'dashboard#show', as: :user_root
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end
end

app/views/nav/_authenticated.html.erb
<div class="flex items-center w-full space-x-8">
  <%= link_to "Jobs", jobs_path, class: "rounded px-2 py-1 text-gray-700 hover:text-gray-900 hover:bg-gray-200" %>
  <%= link_to "Applicants", applicants_path, class: "rounded px-2 py-1 text-gray-700 hover:text-gray-900 hover:bg-gray-200" %>
</div>
<div class="flex items-center justify-end px-6 py-4 flex-shrink-0 space-x-8">
  <%= turbo_stream_from current_user, :notifications %>
  <%= render "nav/notifications", user: current_user %>
  <%= render "nav/settings_menu" %>
  <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "rounded px-2 py-1 text-gray-700 hover:text-gray-900 hover:bg-gray-200" %>
</div>

app/views/nav/_notifications.html.erb
<div data-controller="dropdown" id="notifications-container" class="relative" data-action="click@window->dropdown#hide">
  <button class="py-4 px-1 relative border-2 border-transparent text-gray-800 rounded-full" id="notifications-menu" data-action="click->dropdown#toggle" aria-expanded="false">
    <span class="sr-only">Notifications</span>
    <%= inline_svg_tag('bell.svg', class: "h-6 w-6") %>
    <% if user.notifications.unread.exists? %>
      <div class="absolute inset-0 object-right-top -mr-6">
        <div id="notification-count" class="inline-flex items-center px-1.5 py-0.5 border-2 border-white rounded-full text-xs font-semibold leading-4 bg-red-500 text-white">
          <%= user.notifications.unread.count %>
        </div>
      </div>
    <% end %>
  </button>
  <div class="dropdown-content absolute w-96 h-96 overflow-y-scroll bg-gray-100 shadow-lg rounded-md ring-1 ring-black ring-opacity-5" data-dropdown-target="content">
    <%= turbo_frame_tag "notifications", src: notifications_path, autoscroll: true, data: { autoscroll_block: "start" } %>
  </div>
</div>

app/views/nav/_settings_menu.html.erb
<div data-controller="dropdown" class="relative" data-action="click@window->dropdown#hide">
  <button class="py-4 px-1 relative border-2 border-transparent text-gray-800 rounded-full" id="settings-menu" data-action="click->dropdown#toggle" aria-expanded="false">
    Settings
  </button>
  <div class="dropdown-content absolute w-48 px-2 py-2 bg-gray-100 shadow-lg rounded-md ring-1 ring-black ring-opacity-5" data-dropdown-target="content">
    <ul class="divide-gray-200 divide-y-2" role="menu" aria-orientation="vertical" aria-labelledby="settings-menu">
      <li class="p-2">
        <%= link_to "Career page", careers_account_path(current_user.account), class: "text-blue-700 hover:text-blue-900", target: "_blank" %>
      </li>
      <li class="p-2">
        <%= link_to "Manage Users", users_path, class: "text-blue-700 hover:text-blue-900" %>
      </li>
    </ul>
  </div>
</div>

app/views/nav/_top_nav.html.erb
<nav class="bg-gray-100 shadow">
  <div class="container mx-auto flex text-gray-700 max-w-screen-2xl">
    <div class="flex flex-shrink-0 items-center px-6 py-4">
      <%= link_to "Hotwired ATS", root_path, class: "rounded px-2 py-1 text-gray-700 hover:text-gray-900 hover:bg-gray-200" %>
    </div>
    <% if user_signed_in? %>
      <%= render "nav/authenticated" %>
    <% else %>
      <%= render "nav/unauthenticated" %>
    <% end %>
  </div>
</nav>

app/views/nav/_unauthenticated.html.erb
<div class="flex items-center ml-12 w-full"></div>
<div class="flex items-center justify-end px-6 py-4 flex-shrink-0 space-x-8">
  <%= link_to "Sign In", new_user_session_path, class: "rounded px-2 py-1 text-gray-700 hover:text-gray-900 hover:bg-gray-200" %>
  <%= link_to "Sign Up", new_user_registration_path, class: "rounded px-2 py-1 text-gray-700 hover:text-gray-900 hover:bg-gray-200" %>
</div>